@startuml class-book-simple
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

class Book {
  + title: String
  + author: String
  + pages: int
  + price: double
}

@enduml
