@startuml
!theme plain

start
if (hasMinLength && hasUpperCase && hasNumber ) then (true)
  :Afficher "Mot de passe valide.";
else (false)
  :Afficher "Le mot de passe ne respecte pas les critères.";
endif
stop

@enduml
