@startuml condition-or-adminrights
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if (hasAdminRights || hasSpecialPermission ) then (true)
  :Afficher "Accès autorisé.";
endif
stop

@enduml
