@startuml condition-if-elseif-else-energy
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if (useSolarPower ) then (true)
  :Afficher "Utilisation de l'énergie solaire.";
else if (useBattery ) then (true)
  :Afficher "Utilisation de la batterie.";
else (false)
  :Afficher "Énergie insuffisante.";
endif
stop

@enduml
