@startuml condition-if-else-password
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if (hasMinLength && hasUpperCase && hasNumber ) then (true)
  :Afficher "Mot de passe valide.";
else (false)
  :Afficher "Le mot de passe ne respecte pas les critères.";
endif
stop

@enduml
