@startuml condition-if-else-canuseservice
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if (canUseService ) then (true)
  :Afficher "Accès autorisé au service.";
else (false)
  :Afficher "Accès refusé.";
endif
stop

@enduml
