@startuml condition-if-elseif-else-localfiles
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if (hasLocalFiles && !hasInternetConnection ) then (true)
  :Afficher "Mode hors ligne activé.";
else if (hasLocalFiles && hasInternetConnection ) then (true)
  :Afficher "Synchronisation des fichiers...";
else (false)
  :Afficher "Aucun fichier disponible.";
endif
stop

@enduml
