@startuml condition-if-else-batterylow
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if (!isBatteryLow ) then (true)
  :Afficher "La batterie est suffisante.";
else (false)
  :Afficher "Veuillez recharger l'appareil.";
endif
stop

@enduml
