@startuml condition-simple-batterylevel
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if (batteryLevel < 20 ) then (true)
  :Afficher "Batterie faible, veuillez recharger.";
endif
stop

@enduml
