@startuml condition-simple-isready
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if (isReady ) then (true)
  :Afficher "Le système est prêt.";
endif
stop

@enduml
