@startuml condition-and-username-null
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

start
if ((username != null) && (username.length() > 0) ) then (true)
  :Afficher "Nom d'utilisatrice valide.";
endif
stop

@enduml
