@startuml
!theme plain

class Animal {
  # name: String
  # age: int
  --
  + Animal(name: String, age: int)
}

class Dog {
  - breed: String
  --
  + Dog(name: String, age: int, breed: String)
}

Animal <|-- Dog

note right of Dog::Dog
  super(name, age)
end note

@enduml
