@startuml parent-child-override
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

class Parent {
  + greet(): void
}

class Child {
  + greet(): void
}

Parent <|-- Child



@enduml