@startuml shape-circle-rectangle
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

abstract class Shape {
  # color: String
  --
  + Shape(color: String)
  + {abstract} calculateArea(): double
  + displayColor(): void
}

class Circle {
  - radius: double
  --
  + Circle(color: String, radius: double)
  + calculateArea(): double
}

class Rectangle {
  - width: double
  - height: double
  --
  + Rectangle(color: String, width: double, height: double)
  + calculateArea(): double
}

Shape <|-- Circle
Shape <|-- Rectangle



@enduml