@startuml vehicles-without-inheritance
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

class Car {
  - brand: String
  - model: String
  - year: int
  - numberOfDoors: int
}

class Motorcycle {
  - brand: String
  - model: String
  - year: int
  - hasSidecar: boolean
}

class Truck {
  - brand: String
  - model: String
  - year: int
  - maxLoad: double
}



@enduml